sudo: required
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install -y cmake binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686

script:
    - mkdir build && cd build
    - cmake ../ -DCMAKE_TOOLCHAIN_FILE=../CMakeLists_mingw.txt
    - cmake --build . --target all -- -j2
